export const config = {
    content: {
        logo: "/choroidLogo.png",
        brand: "Ali Al-Ali",
        slogan: "",
        sloganLink: "https://choroidstudios.com",
        metaDescription: "Generated by create next app",

        hero: {
            heroHeadLine: "Tailored MEP Solutions for Optimal Project Performance",
            heroActionText: "",
            heroActionLink: "/services",
            heroSubHeadLine: "Our company strives to provide a comprehensive range of engineering services. In particular, we specialize in delivering MEP (Mechanical, Electrical, and Plumbing) and energy compliance services customized for commercial, residential, and industrial projects situated within California to Florida.",
            parallaxEffect: false,
            heroImageUrl: "/heroImage3.png",
            parallaxImages: [
                'parallax-effect/0.png',
                'parallax-effect/1.png',
                'parallax-effect/2.png',
                'parallax-effect/3.png',
                'parallax-effect/4.png',
            ],
            highlightedHeadlineWords: ["MEP", "Optimal", "Performance"],
            breakLineAfter: ["Solutions", "Project"],
        },
        topPageVectors: "/topPageVectors3.jpg",
        notFoundURL: "/notFound.png",

        links:[
            { path: '/#projects', title: 'Projects' },
            // { path: '/blog', title: 'Blog' },
            { path: '/#solutions', title: 'Solutions' },
            // { path: '/templates', title: 'Templates' },
            { path: '/services', title: 'Services' },
            { path: '/#contact', title: 'Contact' },
        ],

        coreFeatures: {
            isHidden: true,
            mainTitle: "Core Features",
            mainTitleHighlightedWord: "Features",
            data: [
                {
                    icon: "⚡",
                    title: "Swift",
                    description: "Blazing fast load times"
                },
                {
                    icon: "📱",
                    title: "Adaptive",
                    description: "Seamless on all devices"
                },
                {
                    icon: "🎨",
                    title: "Sleek",
                    description: "Modern, eye-catching designs"
                },
                {
                    icon: "🛠️",
                    title: "Flexible",
                    description: "Easily customizable"
                }
            ]
        },
        about: {
            isHidden: true,
            mainTitle: "ABOUT Me",
            mainTitleHighlightedWord: "Me",
            description: "Dedicated professionals committed to delivering innovative web solutions. Our expertise spans across various technologies, ensuring we can meet diverse client needs.",
            buttonText: "CONTACT NOW",
            buttonAction: "#contact",
            aboutImageURL: "/about-us.png",
        },
        projects: {
            isHidden: false,
            mainTitle: "Our Projects",
            mainTitleHighlightedWord: "Projects",
            data: [
                {
                    imageUrl: "/bookifai.jpeg",
                    title: "Bookifai",
                    description: "Ever wanted to connect with the characters in your favourite book and chat with them!? Bookifai allows you to just do that! You upload your favorite book and we extract the characters and create a chatbots for you to interact with them using discord!",
                    actionLink: "mailto:rabeekiblawi@gmail.com",
                    actionText: "Request a Demo",
                    isHidden: false,
                    visibleHome: true
                },
                {
                    imageUrl: "/MirageXR.jpg",
                    title: "MirageXR",
                    description: `Prototype Arduino or ESP projects faster with MirageXR. Our platform connects virtual electronics to your physical hardware, enabling quick testing and development. Using our AR/XR app and Arduino/ESP library, control virtual components with your real board—no extra parts needed.Bridge the physical and virtual worlds in your projects!`,
                    actionLink: "https://www.miragexr.com",
                    actionText: "Join Waitlist",
                    isHidden: false,
                    visibleHome: false
                },
                {
                    imageUrl: "/unity_chatgpt.png",
                    title: "OpenAI Wrapper for Unity",
                    description: "Our Unity package allows you to easily integrate OpenAI's Models into your Unity projects. We provided a simple API that allows you to interact and chain multiple models together to create complex AI behaviors in your game or simulation. Our package is designed to be easy to use and flexible to fit your needs. We also provide a set of example scenes to get you started quickly!",
                    actionLink: "https://github.com/rabeeqiblawi/Choroid-Input-System",
                    actionText: "View On Github",
                    isHidden: false,
                    visibleHome: true
                },
                {
                    imageUrl: "/cfwm2.jpg",
                    title: "Come Fly With Me (Protoype)",
                    description: `Ever wanted to fly like a bird? Come Fly With Me is a VR experience that allows you to do just that! You can fly and explore the world from a bird's eye view!`,
                    actionLink: "https://www.youtube.com/watch?v=oted6xBF0z8",
                    actionText: "More",
                    isHidden: false,
                    visibleHome: false
                },
                {
                    imageUrl: "/notFound.png",
                    title: "test (not at Home page)",
                    description: "TEST",
                    actionLink: "",
                    actionText: "View Project",
                    isHidden: true,
                    visibleHome: false
                },
            ]
        },
        services: {
            isHidden: false,
            mainTitle: "Our Services",
            mainTitleHighlightedWord: "Services",
            data: [
                {
                    title: "MEP Design",
                    description: "Our MEP services integrate essential systems to create efficient, comfortable, and functional environments. We focus on precise heat load calculations, ventilation needs, and selecting cost-effective equipment. By leveraging existing systems and ensuring compliance with energy codes, we deliver optimal, eco-friendly solutions.",
                    icon: "/icons/MEP-Design.svg",
                    actionLink: "https://example.com/digital-marketing-services",
                    actionText: "",
                    isHidden: false,
                    visibleHome: true,
                    comingSoon: false
                },
                {
                    title: "T24",
                    description: "Expertly navigating Title 24 regulations, we ensure that all aspects of your project, from HVAC to lighting and insulation, meet stringent energy compliance standards. Our meticulous approach guarantees that your building projects align seamlessly with California's energy codes.",
                    icon: "/icons/Title24.svg",
                    actionLink: "https://example.com/cloud-computing-services",
                    actionText: "",
                    isHidden: false,
                    visibleHome: true,
                    comingSoon: false
                },
                {
                    title: "Energy Compliance",
                    description: "Offers expert COMcheck and REScheck services for projects across the USA. Ensure your building meets all energy code requirements with our efficient and accurate compliance solutions. Contact us today for streamlined energy code compliance!",
                    icon: "/icons/Energy-Compliance.svg",
                    actionLink: "https://example.com/digital-marketing-services",
                    actionText: "",
                    isHidden: false,
                    visibleHome: true,
                    comingSoon: false
                },
                {
                    title: "Firefighting & Fire Alarm Systems",
                    description: "With a strong focus on safety and innovation, our firefighting and fire alarm solutions provide robust protection against fire hazards. We design and implement systems that meet the highest standards of safety, ensuring your building is well-protected.",
                    icon: "/icons/fire-hydrant.svg",
                    actionLink: "https://example.com/cloud-computing-services",
                    actionText: "",
                    isHidden: false,
                    visibleHome: true,
                    comingSoon: false
                },
                {
                    title: "Architectural Designs",
                    description: "We excel in crafting architectural designs that harmonize aesthetics with functionality. Our expertise in shaping spaces caters to various project types, ensuring that each design not only looks good but also meets practical needs and regulatory standards.",
                    icon: "/icons/architectural-designs.svg",
                    actionLink: "https://example.com/vr-development-services",
                    actionText: "",
                    isHidden: false,
                    visibleHome: true,
                    comingSoon: false
                },
                {
                    title: "JSD Manual",
                    description: "Specializes in Manual J calculations to determine the precise HVAC capacity needed for your building. Our expert services help HVAC installers, technicians, and contractors accurately size equipment for efficient heating and cooling. Ensure optimal performance and energy efficiency with our reliable load calculation solutions.",
                    icon: "/icons/JSD-Manual.svg",
                    actionLink: "https://example.com/bot-development-services",
                    actionText: "",
                    isHidden: false,
                    visibleHome: true,
                    comingSoon: false
                },
            ]
        },  
        solutions: {
            isHidden: false,
            mainTitle: "Our Solutions",
            mainTitleHighlightedWord: "Solutions",
            data: [
                {
                    imageUrl: "",
                    icon: "/icons/Building-Solutions.svg",
                    title: "Comprehensive Building Solutions for Optimal Comfort",
                    description: `We offer a comprehensive range of techniques to create the perfect atmosphere in your building, ensuring optimal comfort and performance throughout all seasons. Our solutions include the latest advancements in plumbing technology, tailored to meet your specific requirements and fully compliant with state codes.`,
                    actionLink: "",
                    actionText: "",
                    isHidden: false,
                    visibleHome: true,
                    comingSoon: false
                },
                {
                    imageUrl: "",
                    icon: "/icons/fire-hydrant.svg",
                    title: "Introducing Our Fire Fighting Design Services",
                    description: `We are excited to announce the launch of our new fire fighting design services. Our expert team provides comprehensive fire protection solutions tailored to safeguard your property and ensure compliance with all safety regulations. From initial design to final implementation, we are dedicated to delivering the highest standards of safety and efficiency. Trust us to protect what matters most.`,
                    actionLink: "",
                    actionText: "",
                    isHidden: false,
                    visibleHome: true,
                    comingSoon: false
                },
                {
                    imageUrl: "",
                    icon: "/icons/Title24.svg",
                    title: "Ensuring Title 24 Compliance",
                    description: "You can be assured of full compliance with Title 24 projects. Our team of experts is adept at identifying and resolving potential issues, leveraging extensive experience with energy compliance software to ensure all requirements are met efficiently and accurately.",
                    actionLink: "https://cyberweavers.choroidstudios.com",
                    actionText: "",
                    isHidden: false,
                    visibleHome: true,
                    comingSoon: false
                },
            ]
        },
        team: {
            isHidden: true,
            mainTitle: "Meet the Team",
            mainTitleHighlightedWord: "Team",
            members: [
                {
                    imageUrl: "/team/diaa.jpg",
                    title: "Diaa AbuAllul",
                    description: "Creative designer with a passion for user experience and visual storytelling.",
                    visibleHome: true
                },
                {
                    imageUrl: "/team/hadiDiab.png",
                    title: "Hadi Diab",
                    description: "Software engineer specializing in front-end development and UI/UX design.",
                    visibleHome: true
                },
                {
                    imageUrl: "/team/karloRajić.png",
                    title: "Karlo Rajić",
                    description: "Frontend developer/Game Level Designer, Karlo has the taste for the best designs",
                    visibleHome: true
                },
                {
                    imageUrl: "/team/mohammadOthman.png",
                    title: "Mohmmad Othman",
                    description: "Graphic Designer, experienced in creating visual concepts and storytelling.",
                    visibleHome: true
                },
                {
                    imageUrl: "/team/shahbaz.jpg",
                    title: "Mohammad Shahbaz",
                    description: "Backend, Mobile, and every thing low level. Currently focusing on mobile and reverse engineering",
                    visibleHome: true
                },
                {
                    imageUrl: "/team/mustafaZabet.png",
                    title: "Mustafa Zabet",
                    description: "Software engineer specializing in front-end development and UI/UX design.",
                    visibleHome: true
                },
                {
                    imageUrl: "",
                    title: "Nizar Sadek",
                    description: "Creative Game level artist/designer experienced in creating high quality optimized game props and enviroments.",
                    visibleHome: true
                },
                {
                    imageUrl: "/team/rabeeQablawi.png",
                    title: "Rabee Qiblawi",
                    description: "Software Engineer, devoted for problem solving, with epxerience in Game Development and XR.",
                    visibleHome: true,
                    isPremium: false
                }
            ]
        },
        clients: {
            isHidden: true,
            title: "Take a look at our clients",
            subtitle: "We did a great job with these companies. You can be next in such elite!",
            buttonText: "Try our path",
            buttonAction: "",
            clientList: [
                { name: "BBC", logo: "/logos/bbc.svg" },
                { name: "The New York Times", logo: "/logos/nyt.svg" },
                { name: "The Economist", logo: "/logos/economist.svg" },
                { name: "Aston Martin", logo: "/logos/aston-martin.svg" },
                { name: "Tesco", logo: "/logos/tesco.svg" },
                { name: "Arsenal", logo: "/logos/arsenal.svg" },
                { name: "London 2012", logo: "/logos/london-2012.svg" },
                { name: "Mercedes-Benz", logo: "/logos/mercedes.svg" },
                { name: "Google", logo: "/logos/google.svg" },
                { name: "Instagram", logo: "/logos/instagram.svg" }
            ]
        },
        clientProjects: {
            isHidden: true,
            mainTitle: "Other Projects",
            mainTitleHighlightedWord: "Projects",
            data: [
                {
                    imageUrl: "/bookifai.jpeg",
                    title: "Bookifai",
                    description: "Ever wanted to connect",
                    actionLink: "mailto:rabeekiblawi@gmail.com",
                    isHidden: false,
                    visibleHome: true
                },
                {
                    imageUrl: "/MirageXR.jpg",
                    title: "MirageXR",
                    description: "Prototype Arduino or ESP miragexr.com",
                    actionLink: "https://github.com/rabeeqiblawi/Choroid-Input-System",
                    isHidden: false,
                    visibleHome: false
                },
                {
                    imageUrl: "/unity_chatgpt.png",
                    title: "OpenAI Wrapper for Unity",
                    description: "Our Unity package allows you to easily",
                    actionLink: "https://github.com/rabeeqiblawi/Choroid-Input-System",
                    isHidden: false,
                    visibleHome: true
                },
                {
                    imageUrl: "/cfwm2.jpg",
                    title: "Come Fly With Me (Protoype)",
                    description: "Ever wanted to fly like a bird?",
                    actionLink: "https://www.youtube.com/watch?v=oted6xBF0z8",
                    isHidden: false,
                    visibleHome: false
                },
                {
                    imageUrl: "/notFound.png",
                    title: "test (not at Home page)",
                    description: "TEST",
                    actionLink: "",
                    isHidden: true,
                    visibleHome: false
                },
            ]
        },
        testimonial: {
            isHidden: true,
            leftQuoteIconURL: "/icons/left-quote.svg",
            rightQuoteIconURL: "/icons/right-quote.svg",
            data: [
                {
                    text: "Hasan's skills in web development are outstanding. We worked together on building websites for four international NGOs, and his creativity and professionalism were impressive. He's a reliable teammate and a valuable addition to any project.",
                    author: "1Abdallah Kpbrosli",
                    authorImageURL: "/team/defaultPerson.png",
                    title: "CDMP"
                },
                {
                    text: "Hasan is a WordPress magician, a wizard of his craft. Whenever I have a WordPress project, no matter how complicated, I know I can count on him to take on and deliver what is beyond my expectations. HIGHLY recommended.",
                    author: "2Amadeus Awad",
                    authorImageURL: "/team/defaultPerson.png",
                    title: "Business Coach - Founder of alt^ people"
                },
                {
                    text: "Hasan is an exceptional developer with expertise in both back-end and front-end development. His collaborative spirit and patience make him a pleasure to work with. He's more than just a coder; he's a great team player.",
                    author: "3Aghny Jreige",
                    authorImageURL: "/team/defaultPerson.png",
                    title: "Brand Strategist - Mute Designs"
                },
                {
                    text: "Hasan is an exceptional developer with expertise in both back-end and front-end development. His collaborative spirit and patience make him a pleasure to work with. He's more than just a coder; he's a great team player.",
                    author: "4Aghny Jreige",
                    authorImageURL: "/team/defaultPerson.png",
                    title: "Brand Strategist - Mute Designs"
                },
                {
                    text: "Hasan is an exceptional developer with expertise in both back-end and front-end development. His collaborative spirit and patience make him a pleasure to work with. He's more than just a coder; he's a great team player.",
                    author: "5Aghny Jreige",
                    authorImageURL: "/team/defaultPerson.png",
                    title: "Brand Strategist - Mute Designs"
                }
            ],
        }
    },
    screenSizes: {
        small: 768,
        medium: 1024,
        large: 1440,
    },
    github: {
        repoOwner: "rabeeqiblawi",
        repoName: "Articles",
    },
    theme: {
        colors: {
            dark: {
                primary: "#3f51b5",
                secondary: "#f50057",
                accent: "#ff4081",
                background: "#212121",
                surface: "#424242",
                error: "#b00020",
            },
            light: {
                primary: "#3f51b5",
                secondary: "#f50057",
                accent: "#ff4081",
                background: "#f5f5f5",
                surface: "#ffffff",
                error: "#b00020",
            },
        },
        fonts: {
            primary: "Roboto, sans-serif",
            secondary: "Roboto, sans-serif",
        },
    },
    socialLinks: {
        github: "",
        linkedin: "",
        twitter: "",
        facebook: "",
        instagram: "",
        tiktok: "",
        youtube: "",
    },
    contact: {
        imageUrl: "/contact-us.png",
        mainTitle: "Contact Us",
        mainTitleHighlightedWord: "Us",
        title: "Get in Touch",
        description: "We're here to help and answer any question you might have. We look forward to hearing from you!",
        buttonText: "Send us a message",
        isHidden: false,

        contactInfo: {
            phone: "+961  76827526",
            mail: "ali.mustafa.alali.94@gmail.com",
            location: "Beirut, LB",
            whatsappMessage: ""
        }
    },
    featureFlags: {

    },
    apiEndpoints: {
        githubBlogs: "/api/github-blogs",
    },
};